services:
  homelab-dashboad-front:
    container_name: homelab-dashboard-front
    image: ghcr.io/jaumoso/homelab-dashboard-front:latest
    ports:
      - 4200:80
    depends_on:
      - homelab-dashboard-back
    networks:
      - homelab-dashboard

  homelab-dashboard-back:
    container_name: homelab-dashboard-back
    image: ghcr.io/jaumoso/homelab-dashboard-back:latest
    ports:
      - 3000:3000
    networks:
      - homelab-dashboard

networks:
  homelab-dashboard:
    driver: bridge