services:
  homelab-dashboard:
    container_name: homelab-dashboard
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./server/db:/app/db
      # - /var/run/docker.sock:/var/run/docker.sock