services:
  homelab-dashboard:
    container_name: homelab-dashboard
    image: ghcr.io/jaumoso/homelab-dashboard:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./database:/app/server/db
      # - /var/run/docker.sock:/var/run/docker.sock